// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrEX7hbvWJ4Vsj5Qmth3w8t0LpHEteASI',
    appId: '1:491852447109:android:34bb6e1dc475e1313518ec',
    messagingSenderId: '491852447109',
    projectId: 'zoommeeting-5b075',
    storageBucket: 'zoommeeting-5b075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUv_HszzOisyy57p80nsUXCvHlsFuAqMU',
    appId: '1:491852447109:ios:c05a8d39e13c46913518ec',
    messagingSenderId: '491852447109',
    projectId: 'zoommeeting-5b075',
    storageBucket: 'zoommeeting-5b075.firebasestorage.app',
    androidClientId: '491852447109-qbtqpkd42k430ofcvfc3ho3gpa9bgkp5.apps.googleusercontent.com',
    iosClientId: '491852447109-9j2arook9a4q43b36m0requco2on3c2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomclone',
  );
}
